config/routes.rb
Rails.application.routes.draw do

  
  
  
   root 'pages#home'
   get 'pages/about', to: 'pages#about'

   resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  

end

app/models/concerns/article.rb
class Article < ActiveRecord::Base 
    belongs_to :user
    validates  :title, presence: true, length: {minimum: 3, maximum:50}
    validates  :description, presence: true,  length: {minimum: 5, maximum:50}
    validates  :user_id, presence: true
 
 #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

   # validates :email, presence: true, length: { maximum: 105 },
   # uniqueness: { case_sensitive: false },
   # format: { with: VALID_EMAIL_REGEX }

end

app/models/concerns/user.rb
class User < ActiveRecord::Base 
     has_many :articles
     before_save {self.email = email.downcase}
     validates :username, presence: true, 
              uniqueness: {case_sensitive: false}, 
              length:{minimum: 3, maximum: 20}
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email, presence: true, length: {maximum: 105},
              uniqueness: {case_sensitive: false},
              format: {with: VALID_EMAIL_REGEX}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You Must be logged in to execute this Action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]


    
   def index 
       @articles = Article.paginate(page: params[:page], per_page: 5)
   end    
    
   def new
        @article = Article.new
   end
   
   def edit
   end
                
    
   def create
       @article = Article.new(article_params)
       @article.user = current_user
            if  @article.save 
                flash[:success] = "Article was successfully created"
                redirect_to article_path(@article)
                
            else
                render 'new'
            end
   end
    
    def update
       
        if @article.update(article_params) 
                flash[:success] = "your article was updated"
                redirect_to article_path(@article)
        else 
               render 'edit'
    end

    def show
     
    end    
            
    end
    
    
    def destroy
         
         @article.destroy
             flash[:danger] = "Article deleted"
             redirect_to  articles_path
        end
          
          
    end
    

    #private information keys
    
    private
    
        def set_article
            @article = Article.find(params[:id])
        end
     
    
     def article_params
         params.require(:article).permit(:title, :description)
        end
    
    def require_same_user
        if current_user != @article.user
            flash[:danger] = "You do not have clearance to make these changes"
            redirect_to root_path
        end
    end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
      redirect_to articles_path  if logged_in?
    end
end
    
    def about
    end
        

app/controllers/sessions_controller.rb
 class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create 
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end
  
  def destroy 
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :set_user, only: [:edit, :update, :show]
before_action :require_same_user, only: [:edit, :update]


  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  
  def new 
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
        flash[:success] = "Welcome to the alpha blog #{@user.username}"
        redirect_to user_path(@user)
    else
        render 'new'
    end
  end

  def edit 
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end 
  def show
    @user_articles = User.paginate(page: params[:page], per_page: 5)
  end

  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  
    def require_same_user
      if !logged_in? && current_user != @user
        flash[:danger] = "You can only edit your own account"
        redirect_to root_path
      end 
    end
    
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
    
def gravatar_for(user, options = { size: 160})
       gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
       size = options[:size]
       gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
       image_tag(gravatar_url, alt: user.username, class: "img-circle")
end
end

app/views/articles/_article.html.erb
<h3 align="center"><%= link_to 'Home', root_path %></h3>

            <% obj.each do |article| %>
            
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class= "well well-lg">
            <div class="article-title">
                  <%= link_to article.title, article_path(article) %>
            </div>    
            
          <div class="article-body">      
              <%= truncate(article.description, length: 100) %>
             
             <div class = "article-meta-details">
              <small> 
                      Created by: <%= article.user.username %>, 
                      <%= time_ago_in_words(article.created_at) %> ago,
                      last updated: <%= time_ago_in_words(article.updated_at) %> ago,
              </small>
              </div>
          </div>    
          <% if logged_in? && current_user == article.user %>
              <div class="article-actions">
                    <%= link_to 'Edit this Article', edit_article_path(article), class: "btn btn-xs btn-primary" %> 
                    <%= link_to 'delete this article', article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>
                </div>
          <% end %>    
          </div>     
        </div> 
      </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'layouts/shared/errors', obj: @article %>

<div class = 'row'>
     <div class = 'col-xs-8'> 
          <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <div class = 'form-group'>
         <div class = 'control-lable-col-sm-2'>
            <%= f.label :title %> 
        </div>
    <div class ='col-sm-8'>    
        <%= f.text_field :title, class: "form-control", placeholder:"Name of Title", autofocus: true  %>
    </div>    
     
    </div>
    
    <div class = 'form-group'>
        <div class = 'col-xs-8'> 
          <%= f.label :description  %> 
        </div>    
    
        <div class = 'col-xs-10'>
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder:"Body of Article", autofocus: true  %>
        </div>
    </div>
    
    <br/>
    
    <div class = "form-group">
        <div class = "col-sm-10 col-sm-offset-0">
            <%= f.submit class: "btn btn-primary btn-large" %>
        </div>
    </div>
    
<% end %>

<div class = "col-xs-6 col-offset-6">
[<%= link_to 'Cancel request and back to Article Listings', articles_path %>]
</div>
         
       

app/views/articles/edit.html.erb
<h1 align = "center">Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Article Listings</h1>
    <div align = "center">
        <%= will_paginate %>
    </div>
 <%= render 'article', obj: @articles %>
  
  <div align = "center">
        <%= will_paginate %>
    </div>

app/views/articles/new.html.erb
<h1 align="center">Create Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 align="center">Showing Article</h1>
    
   <h3 align="center"> Title: <%= @article.title %> </h2>
<% if @article.user %>
<div class="well col-xs-8 col-xs-offset-2">
    <ul class ="listing">
         <div class = "row center">
             <div class= "col-md-4 col-md-offset-4">
                 <li>Created By:</li>
                 <li> <%= link_to gravatar_for(@article.user), user_path(@article.user)  %> </li>
                 <li class="article-title"> <%= link_to @article.user.username, user_path(@article.user) %> </li>
                 <li><small> <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %> </small></li>
             </div>
         </div>
     </ul>
     <% end %>
    <h4 align="center description"<strong> Description:</strong></h4>
    <hr>
    
   <%= simple_format(@article.description) %>
   
   <div class = "article-actions">
     <% if logged_in? && current_user == @article.user %>
        <%= link_to 'Edit this Article', edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
        <%= link_to 'delete this article', article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>
    <% end %> 
        <%= link_to 'View all articles', articles_path, class: "btn btn-xs btn-success" %>   
      
        </div>
    </div>
    
 

app/views/layouts/_footer.html.erb
<div class = "container">
    <footer class = "footer">
        <small>
            Copyright &copy; <a href "www.removingthefuzz.com"> Justin Lee </a> by Justin Lee
        </small>
    <nav>
        <ul>
            <li> <%= link_to "About", pages_about_path %> </li>
        </ul>
    </nav>
    
    </footer>
    

app/views/layouts/_messages.html.erb
<div class = "row"> 
    <div class = "col-xs-10 col-offset-1">

<% flash.each do |name, msg| %> 
   <div class='alert alert-<%="#{name}" %>'> 
   <a href="#" class = "close" data-dismiss = "alert">&#215;</a>
       <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
     </div>
        <% end %>
    </div>
 </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "Justins Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to "Fuzz Busters", users_path%></li>
        <% if logged_in? %>
            <li><%= link_to "Articles", articles_path %></li>
            <li> <%= link_to "About", pages_about_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "New Article", new_article_path %></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
          <% end %>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Logout', logout_path, method: :delete %></li> 
          <li></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li> <%= link_to "Edit Your Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View Your Profile", user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
          <% else %>
            <li><%= link_to 'Login', login_path %></li> 
            <li><%= link_to 'Sign Up', signup_path %></li>
          <% end %>  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ABlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    
   
    <div class ="container">
      <%= yield %>
    </div>
    
    
       <%= render 'layouts/footer' %> 
 
    
</body>



</html>

app/views/layouts/shared/_errors.html.erb
<% if obj.errors.any? %>
 <div class ="row">
     <div class = "col-xs-8 col-xs-offset-2">
         <div class="panel panel-danger">
             <div class = "panel-heading">
                 <h2 class = "panel-title">
                     <%= pluralize(obj.errors.count,"error") %>
                     prevented your action
                 </h2>
                 
                 <div class = "panel-body">
                     <ul>
                      <% obj.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                      <% end %>
                            
                     </ul>    
                  </div>
                </div> 
            </div> 
        </div> 
    </div> 
 <% end %>

app/views/pages/about.html.erb
<html>
<head>
 <title> about </title>
 <meta charset="utf-8" />
 <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
 <meta name="viewport" content="width=device-width, initial-scale=1" />
 <meta name="viewport" content="width=device-width, initial-scale=1" />
 <meta name="description" content="A jouney of a thousand miles begins with a
single step. This is step 2" />
</head>

	<h3 class = "center"><%= link_to "Home-base", root_path %></h3>

<h1>This is the about page of the application</h1>

<h2>This is where you can read all about me in less than 500 *2 words or so give or take a few on either side</h2>

<hr>

    <h1>Justins Bio</h1>

        <p>Justin doesn’t usually talk in the third person but for the next section of reading we will refer to Justin as the supreme J of "ustin", Justin is an active martial arts athlete and world traveler</p>
        <p>Justin likes to do many things and learning to develop apps in Ruby has been a recent obsession, and programming with a touch of cpu-sci has been an interest for a couple of years</p>
        <p>Justin is currently residing in the Seoul of Asia <strong>*Cough South Korea</strong> and he really enjoys the hot summers here as well as the delicious food and beautiful....wo...scenery</p>
        <p>Although this blog perhaps will be published as a shit bag disaster, i can redirect you to the complaints page where your complaints will be lost to the void...forever :)</p>
        <p>On a serious note, Justin really enjoys an active lifestyle in Korea, and is actively pursuing athletic and professional goals</p>
<br>

    <h1>Justins Working life in Korea</h1>
        <p><strong>Justins</strong>, <i>lighting quick wit</i>, and determination has landed him in various occupations throughout his life. Justin has worked in the following <i>ordered lists</i> for your reading ease</p>
            <ol>
                <li>Picking up rotting garbage off the road in high school</li>
                <li>The Canadian armed forces as a combat Engineer, Chimo!</li>
                <li>A bus boy and bar hand in various drinking dens in the St. Johns, Newfoundland area</li>
                <li>Working and investing in start-up companies back in the rock (Newfoundland)</li>
                <li>A student at Memorial University and Hanyang Universities in Canada & Korea</li>
                <li>working in South Korea both corporate and a teacher</li>
                <li>an aspiring game/web developer, right now a Student of Ruby <strong>:D*</strong></li>
            </ol>
    
    <p>That is all for now mortals. Check back when i learn how to style this bad boy with bootstrap and other wizardry</p>
    

app/views/pages/home.html.erb
<html>
<head>
 <title> home </title>
 <meta charset="utf-8" />
 <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
 <meta name="viewport" content="width=device-width, initial-scale=1" />
 <meta name="viewport" content="width=device-width, initial-scale=1" />
 <meta name="description" content="A jouney of a thousand miles begins with a
single step." />
</head>

<div class="center jumbotron">
  <h1>JUSTINS BLOG</h1>
 <%= link_to "Sign Up Now", signup_path, class: 'btn btn-danger btn-xlarge' %> 
</div>


<body>
<a name="top"></a>
	<h1>Web - J and Random</h1>
	
	<%= link_to "Alpha Blog", articles_path %> | <%= link_to "about", pages_about_path %>
	

	 
		<p>This will be justins digital home for the next 50 million years</p>
		<p>This is also Justins very first runy on rails web blog that he has created(creating)</p>
	
	 	
	<p>This is an unordered list of Justins favourite foods:</p>
	 	
<ul>
	 	 <li>Tangerines</li>
	 	 <li>DDokboKKie</li>
	 	 <li>Apples</li>
</ul>
 
<!-- <a href="#top">Click me to go to the top of the page</a> -->
	 	
	 	
</body>
</html>

app/views/users/_form.html.erb
<%= render 'layouts/shared/errors', obj: @user %>

<div class = 'row'>
     <div class = 'col-xs-8'> 
          <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <div class = 'form-group'>
         <div class = 'control-lable-col-sm-2'>
            <%= f.label :username %> 
        </div>
    <div class ='col-sm-8'>    
        <%= f.text_field :username, class: "form-control", placeholder:"enter username", autofocus: true  %>
    </div>    
     
    </div>
    
    <div class = 'form-group'>
        <div class = 'col-xs-8'> 
          <%= f.label :email  %> 
        </div>    
    
        <div class = 'col-xs-8'>
            <%= f.email_field :email, class: "form-control", placeholder:"enter email", autofocus: true  %>
        </div>
    </div>
    
    <div class = 'form-group'>
        <div class = 'col-xs-8'> 
          <%= f.label :password %> 
        </div>    
    
        <div class = 'col-xs-8'>
            <%= f.password_field :password, class: "form-control", placeholder:"enter password", autofocus: true  %>
        </div>
    </div>
    
    
    <br/>
    
    <div class = "form-group">
        <div class = "col-sm-10 col-sm-offset-0">
            <%= f.submit(@user.new_record? ? "Sign Up": "Update Account", class: "btn btn-primary btn-large") %>
        </div>
    </div>
    
<% end %>

<div class = "col-xs-6 col-offset-6">
[<%= link_to 'Cancel request and back to Article Listings', articles_path %>]
        </div>
     </div>       
   </div>

app/views/users/edit.html.erb
<h1 align='center'> Edit Your Account</h1>

    <%= render 'form' %> 

app/views/users/index.html.erb
<h1 class="center"> All Fuzz Busters</h1>
<div align ="center"> 
        <%= will_paginate %>
 <%= @users.each do |user| %> 
     <ul class ="listing">
         <div class = "row">
             <div class= "well col-md-4 col-md-offset-4">
                 <li> <%= link_to gravatar_for(user), user_path(user)  %> </li>
                 <li class="article-title"> <%= link_to user.username, user_path(user) %> </li>
                 <li><small> <%= pluralize(user.articles.count, "article") if user.articles %> </small></li>
             </div>
         </div>
     </ul>
   <% end %> 
   <%= will_paginate %>
</div>   

app/views/users/new.html.erb
<h1 align='center'> Sign up for the RTF blog </h1>

    <%= render 'form' %>

app/views/users/show.html.erb
    <h1 class="center"> Welcome to <%= @user.username %>'s page </h1>
        <div class = "row">
            <div class = "col-md-4 col-md-offset-4 center">
            
           <%= gravatar_for @user %> 
            
            </div>
        </div>
     
     <h4 align="center"> These are <%= @user.username %>'s Articles</h4>
         <div class = "center">
             <%= will_paginate @user_articles %>
             <%= render 'articles/article', obj: @user.articles %>
        </div>
         